sudo: required

language: cpp

matrix:
  include:
      env: 
        - IMAGE=fedora:25
  allow_failures:
      env: 
        - IMAGE=fedora:latest

services:
  - docker

before_install:
  - docker --version
  - docker run -d --name image-build -v $(pwd):/travis $IMAGE tail -f /dev/null
  - docker ps

install:
  - docker exec -t image-build bash -c "dnf update -y && dnf install openssl openssl-static libp11-devel gcc-c++ make gtest-devel -y"

script:
  - docker exec -t image-build bash -c "cd /travis && ls && openssl version"
  - docker exec -t image-build bash -c "cd /travis && make SSL_INCLUDES='/usr/include/'  LIBS_STATIC='/usr/lib64/libcrypto.a /usr/lib64/libssl.a -lp11' static -j `nproc` && make install"
  - docker exec -t image-build bash -c "cd /travis/tests && make SSL_INNCLUDES='/usr/include/' test -j `nproc`"
