language: cpp

compiler:
- g++

sudo: false

before_install:
- pip install --user cpp-coveralls

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    
script:
- make CC=g++-4.9 USER_OBJS=/usr/lib/x86_64-linux-gnu/libcrypto.so

