sudo: required

language: cpp

matrix:
  include:
      env: 
        - IMAGE=fedora:25
  allow_failures:
      env: 
        - IMAGE=fedora:latest

services:
  - docker

before_install:
  - docker --version
  - docker run -d --name image-build -v $(pwd):/travis $IMAGE tail -f /dev/null
  - docker ps

install:
  - docker exec -t image-build bash -c "dnf update -y && dnf install openssl-static libp11-devel gcc-c++ make"

script:
  - docker exec -t image-build bash -c "cd /travis && ls && openssl version && make -j `nproc` && make install && make 'LIBS=-lcryptosec -lgtest' -C tests test"
